Need to catch SystemCommandNonzeroExit too
Closer inspection of the error in the log showed that the system call
was succeeding, but the exit code being non-zero triggered a different
exception: SystemCommandNonzeroExit. Catching SystemCommandError will
catch both SystemCommandNonzeroExit and SystemCommandExecutionError.

(hopefully) fixes #883